Main view has been converted to TS. TS conversion is basically complete.
The TS error:

error TS2140: 'this' cannot be referenced in initializers in a class body.
can be ignored, see: https://typescript.codeplex.com/discussions/447071

It resolves a whole number of problems with "this" contexts in event handlers and callback functions.